No SQL database webpage
ScifiAN/Kurs-Programowania pull request #19
Opened 2022-02-23 21:38 UTC by ScifiAN

2022-03-05 21:43 UTC, Kameq requested changes

2022-03-05 21:43 UTC, Kameq commented on Project-no-sql-website/routes/blog.js
> +  console.log(result);
remove console.log

2022-03-05 21:43 UTC, Kameq commented on Project-no-sql-website/app.js
> +  console.log(error);
console.log

2022-03-06 17:30 UTC, ScifiAN commented
Removed console logs

2022-03-15 10:11 UTC, merged