Working with ajax
ScifiAN/Kurs-Programowania pull request #21
Opened 2022-02-26 15:38 UTC by ScifiAN

2022-03-05 21:18 UTC, Kameq requested changes

2022-03-05 21:18 UTC, Kameq commented on Project-AJAX/app.js
> +  console.log(error);
remove console.log

2022-03-05 21:18 UTC, Kameq commented on Project-AJAX/routes/blog.js
> +  console.log(result);
console.log again

2022-03-06 17:22 UTC, ScifiAN commented
Fixed console logs

2022-03-15 10:12 UTC, merged