Practising with authentication, sessions, cookies and authorization
ScifiAN/Kurs-Programowania pull request #22
Opened 2022-03-01 09:21 UTC by ScifiAN

2022-03-05 21:43 UTC, Kameq requested changes

2022-03-05 21:43 UTC, Kameq commented on Project-authentication/app.js
> +  secret: 'super-secret',
homework:

in the scope of hardcoded `secret` here research on google how to handle sensitive data ex. passwords etc 

read about `.env` file for node/react/js projects

2022-03-05 21:43 UTC, Kameq commented on Project-authentication/routes/demo.js
> +    !enteredEmail ||
the best way to format multi line if case is this one 

```
!enteredEmail
|| !enteredConfirmEmail
|| ...
```
so OR's or AND's are first in line

2022-03-06 17:26 UTC, ScifiAN commented
Corrected

2022-03-15 10:11 UTC, merged